# fly.toml app configuration file generated for gnometeaparty-redirect on 2024-11-30T14:38:34+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gnometeaparty-redirect'
primary_region = 'ams'

[build]
  dockerfile = './Dockerfile'

[deploy]
  strategy = 'bluegreen'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
